SELECT COUNT( * ) FROM COMPANIES
WHERE NAME LIKE '%.com'
AND CITY IN('Bangkok', 'Brussels')

SELECT TOP 5 CITY, COUNT(CITY) FROM COMPANIES
GROUP BY CITY ORDER BY COUNT(CITY) DESC;


SELECT DISTINCT K_COMPANY, NAME FROM COMPANIES
WHERE K_COMPANY IN(SELECT K_COMPANY FROM CONT_COMP)

SELECT * FROM COMPANIES INNER JOIN
CONT_COMP ON(COMPANIES.K_COMPANY = CONT_COMP.K_COMPANY)
INNER JOIN CONTACTS ON(CONTACTS.K_CONTACT = CONT_COMP.K_CONTACT)
ORDER BY COMPANIES.NAME ASC, CONTACTS.NAME DESC


SELECT COUNT(NAME) FROM CONTACTS
WHERE CONTACTS.K_CONTACT NOT IN(SELECT K_CONTACT FROM CONT_COMP)